"""`pedroc verify` — tamper-evidence for generated output.

Reads the source hash stamped in a generated file's banner, recomputes the hash
of the current `.pedro` source, and reports whether they still agree. A mismatch
has two distinct meanings, and this module distinguishes them:

- **stale** — the source hash changed, so the `.pedro` file was edited after the
  output was generated. Rebuild the output.
- **drift (hand-edited)** — the hash still matches the source, but the generated
  file's bytes no longer match what pedroc produces from that source, so the
  generated file was hand-edited after the fact (someone bypassed the compiler).

The banner hash IS a hash of the *source*, so it is as deterministic as codegen
itself: same source + same compiler version -> same hash -> byte-identical file.
"""
from .hashing import source_hash, parse_banner


def verify(source, generated_text, source_name="<pedro>", output_name="<output>"):
    """Return a structured verify report (same JSON style as `check`).

    `source` is the current `.pedro` source; `generated_text` is the contents of
    the generated file whose banner we trust for the target/filename it recorded.
    """
    report = {
        "ok": False,
        "source": source_name,
        "output": output_name,
        "status": "error",       # match | stale | drift | no-banner | error
        "stamped_hash": None,
        "current_hash": source_hash(source),
        "summary": "",
    }

    banner = parse_banner(generated_text)
    if banner is None:
        report["status"] = "no-banner"
        report["summary"] = (f"{output_name}: no pedroc banner found — not a "
                             "pedroc-generated file (or produced by a compiler "
                             "older than the source-hash banner).")
        return report

    stamped = banner["hash"]
    report["stamped_hash"] = stamped
    report["target"] = banner["target"]

    if stamped == "unknown":
        report["status"] = "no-banner"
        report["summary"] = (f"{output_name}: banner has no source hash "
                             "(source-hash: unknown) — cannot verify.")
        return report

    if stamped != report["current_hash"]:
        # The recorded hash no longer matches the source: the .pedro changed.
        report["status"] = "stale"
        report["summary"] = (
            f"STALE: {source_name} changed since {output_name} was generated "
            f"(source-hash {stamped} -> {report['current_hash']}); rebuild it.")
        return report

    # Hash matches the source. If the generated bytes still differ from a fresh
    # compile of that source, the generated file itself was hand-edited.
    from . import compile_source  # local import: avoids any import-cycle risk
    try:
        expected = compile_source(source, filename=banner["filename"],
                                  target=banner["target"])
    except Exception as e:  # noqa: BLE001 — surface any recompile failure verbatim
        report["status"] = "error"
        report["summary"] = (f"{source_name}: could not recompile to verify "
                             f"({type(e).__name__}: {e}).")
        return report

    if generated_text == expected:
        report["ok"] = True
        report["status"] = "match"
        report["summary"] = (
            f"OK: {output_name} matches {source_name} (source-hash {stamped}).")
        return report

    report["status"] = "drift"
    report["summary"] = (
        f"DRIFT: {output_name} was hand-edited after generation — its contents "
        f"no longer match what pedroc produces from {source_name} "
        f"(source-hash {stamped}). Regenerate to discard the edits.")
    return report
